version: '3'

services:
  reverse-proxy:
    networks:
      - traefik
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    networks:
      - traefik
    #image: coronawhy/covid_portal:backend
    build: webCovidPortal/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`portaldb.${traefikhost}`)"
      - "traefik.http.routers.backend.entrypoints=web"
  
  frontend:
    networks:
      - traefik
    #image: coronawhy/covid_portal_frontend:portaldb_port80
    build: covidPortalFrontEnd/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portal.${traefikhost}`)"
      - "traefik.http.routers.frontend.entrypoints=web"

networks:
  traefik:
    external: true
