# Generated by Django 2.2 on 2020-05-28 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidPortalApp.Alignment')),
            ],
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gb_taxon_id', models.CharField(max_length=20, unique=True)),
                ('leaf', models.BooleanField()),
                ('path', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='protein',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='sequence',
        ),
        migrations.AddField(
            model_name='protein',
            name='extrez_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='protein',
            name='mesh_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='protein',
            name='uniprot_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='ProteinSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=50, unique=True)),
                ('organism', models.CharField(max_length=200)),
                ('collection_date', models.DateTimeField(null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('host', models.CharField(max_length=100, null=True)),
                ('isolation_source', models.CharField(max_length=100, null=True)),
                ('coded_by', models.CharField(max_length=50, null=True)),
                ('sequence', models.TextField()),
                ('offset', models.IntegerField()),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidPortalApp.Alignment')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidPortalApp.Protein')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidPortalApp.Taxon')),
            ],
        ),
        migrations.CreateModel(
            name='NomenClaturePositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('major', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidPortalApp.Nomenclature')),
            ],
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='reference_proteinSequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='covidPortalApp.ProteinSequence'),
        ),
    ]
