# Generated by Django 3.0.5 on 2020-06-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidPortalApp', '0002_auto_20200528_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteinsequence',
            name='alignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covidPortalApp.Alignment'),
        ),
    ]
