# Generated by Django 2.2.13 on 2020-06-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0019_auto_20200605_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencerecord',
            name='isolation_source',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='StructureChainResidueAlignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resaln', models.IntegerField()),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.StructureChainResidue')),
                ('structure_chain_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.StructureChainSequence')),
            ],
        ),
    ]
